[config]
schemaVersion = "0.0.1"

[package]
namespace = "Caioreix"
name = "ChatHistory"
versionNumber = "0.0.0"
description = "A VRising plugin that enhances chat functionality by allowing players to navigate, and manage their chat history."
websiteUrl = "https://github.com/caioreix/ChatHistory"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_V_Rising = "1.733.2"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./dist"
target = ""

[publish]
repository = "https://thunderstore.io"
communities = ["v-rising"]

[publish.categories]
v-rising = ["oakveil-update", "mods", "client"]
